package cmd

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/lucap123/envy/pkg/detect"
)

func Init(args []string) error {
	pt := detect.Detect()
	fmt.Printf("Detected project type: %s\n", pt)

	if _, err := os.Stat(".env.example"); err == nil {
		fmt.Println(".env.example already exists, skipping.")
		return nil
	}

	vars := detect.GetExampleVars(pt)
	keys := sortedKeys(vars)

	var sb strings.Builder
	sb.WriteString("# Generated by envy\n")
	sb.WriteString(fmt.Sprintf("# Project type: %s\n\n", pt))
	for _, k := range keys {
		sb.WriteString(fmt.Sprintf("%s=%s\n", k, vars[k]))
	}

	if err := os.WriteFile(".env.example", []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("could not create .env.example: %w", err)
	}

	fmt.Println("Created .env.example")
	fmt.Println("Tip: run 'envy set <key> <value>' to store your actual values.")
	return nil
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
