package cmd

import (
	"fmt"
	"os"
	"strings"
	"syscall"

	"github.com/awnumar/memguard"
	"github.com/lucap123/envy/pkg/store"
	"golang.org/x/term"
)

func Set(s *store.Store, key []byte, args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: envy set <key> [value]")
	}

	keyName := args[0]
	var val string

	if len(args) >= 2 {
		// Value provided inline — warn about shell history exposure
		fmt.Fprintf(os.Stderr, "Warning: passing values inline may expose them in shell history.\n")
		fmt.Fprintf(os.Stderr, "Tip: run 'envy set %s' (no value) to enter it securely.\n\n", keyName)
		val = strings.Join(args[1:], " ")
	} else {
		// Interactive prompt — no echo, value never touches the command line
		fmt.Printf("Value for %s: ", keyName)
		raw, err := term.ReadPassword(int(syscall.Stdin))
		fmt.Println()
		if err != nil {
			return fmt.Errorf("failed to read value: %w", err)
		}
		buf := memguard.NewBufferFromBytes(raw)
		defer buf.Destroy()
		val = string(buf.Bytes())
	}

	pv, err := s.Load(key)
	if err != nil {
		return err
	}

	if pv.Profiles[pv.Active] == nil {
		pv.Profiles[pv.Active] = make(map[string]string)
	}
	pv.Profiles[pv.Active][keyName] = val

	if err := s.Save(pv, key); err != nil {
		return err
	}

	fmt.Printf("Set %s in profile '%s'\n", keyName, pv.Active)
	return nil
}

func Get(s *store.Store, key []byte, args []string) error {
	if len(args) < 1 {
		return fmt.Errorf("usage: envy get <key>")
	}

	pv, err := s.Load(key)
	if err != nil {
		return err
	}

	vars := pv.GetActiveVars()
	val, ok := vars[args[0]]
	if !ok {
		return fmt.Errorf("variable '%s' not found in profile '%s'", args[0], pv.Active)
	}

	fmt.Println(val)
	return nil
}

func List(s *store.Store, key []byte, args []string) error {
	reveal := len(args) > 0 && args[0] == "--reveal"

	pv, err := s.Load(key)
	if err != nil {
		return err
	}

	vars := pv.GetActiveVars()
	if len(vars) == 0 {
		fmt.Printf("No variables stored in profile '%s'.\n", pv.Active)
		fmt.Println("Tip: use 'envy set <key> <value>' to add one.")
		return nil
	}

	fmt.Printf("Profile: %s (%d variables)\n\n", pv.Active, len(vars))
	for _, k := range sortedKeys(vars) {
		v := vars[k]
		if !reveal {
			if len(v) <= 4 {
				v = strings.Repeat("*", len(v))
			} else {
				v = v[:2] + strings.Repeat("*", len(v)-4) + v[len(v)-2:]
			}
		}
		fmt.Printf("  %-30s %s\n", k, v)
	}

	if !reveal {
		fmt.Println("\nTip: use 'envy list --reveal' to show full values.")
	}
	return nil
}

func Export(s *store.Store, key []byte, args []string) error {
	outFile := ".env"
	for i, a := range args {
		if a == "--file" && i+1 < len(args) {
			outFile = args[i+1]
		}
	}

	pv, err := s.Load(key)
	if err != nil {
		return err
	}

	vars := pv.GetActiveVars()
	if len(vars) == 0 {
		fmt.Println("No variables to export.")
		return nil
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Generated by envy (profile: %s)\n\n", pv.Active))
	for _, k := range sortedKeys(vars) {
		sb.WriteString(fmt.Sprintf("%s=%s\n", k, vars[k]))
	}

	if err := os.WriteFile(outFile, []byte(sb.String()), 0600); err != nil {
		return fmt.Errorf("could not write %s: %w", outFile, err)
	}

	fmt.Printf("Exported %d variables to %s\n", len(vars), outFile)
	fmt.Printf("Warning: %s contains plaintext secrets. Do not commit it.\n", outFile)
	return nil
}
